[package]
name = "datetime-display"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4"
rocket = "0.5.0-rc.3"

[dependencies.rocket_dyn_templates]
version = "0.1.0-rc.3"
features = ["tera"]
