# Builds on docker-compose.yml
# Mount code for hot reloading and cache for faster compile in dev mode.

# Shared yaml extensions (https://docs.docker.com/compose/compose-file/compose-file-v3/#extension-fields)
# Volume mapping shared between containers.
# Volumes to un-shadow build directories under server are created in the dockerfile.
x-sbt-volumes:
  volumes: &sbt-volumes
    - ./server:/usr/src/server

services:
  dev-oidc:
    ports:
      - 3390:3390

  civiform:
    build: .
    volumes: *sbt-volumes
    stdin_open: true # docker run -i
    tty: true # docker run -t
    restart: always
    ports:
      - 9000:9000
      - 8457:8457

  civiform-shell:
    image: civiform-dev
    entrypoint: /bin/bash
    profiles: ['shell']
    volumes: *sbt-volumes
    stdin_open: true # docker run -i
    tty: true # docker run -t

  localstack:
    # Overrides the localstack image used to work around
    # https://github.com/seattle-uat/civiform/issues/2639.
    # Note that we don't set this in the base template
    # since it's not necessary for CI / browser test runs.
    image: civiform-localstack
    ports:
      - 4566:4566
  azurite:
    ports:
      - 10000:10000

  mock-web-services:
    image: civiform-mock-web-services

  db:
    image: postgres:16.8@sha256:ab395d612697242f2537f57a727c794a6310c194d55996660c40bfc55ddd14c4
    stdin_open: true
    tty: true
    volumes:
      # isolate and persist dev database.
      - project-data:/project
      - db-data:/var/lib/postgresql/data
      - ./init_postgres.sql:/docker-entrypoint-initdb.d/init_postgres.sql

  pgadmin:
    profiles: ['pgadmin']
    image: dpage/pgadmin4:8@sha256:8a68677a97b8c8d1427dc915672a26d2c4a04376916a68256f53d669d6171be7
    restart: always
    depends_on:
      - db
    volumes:
      - /tmp/servers.json:/pgadmin4/servers.json
      - db-data:/var/lib/postgresql/data
    ports:
      - 8012:80
    environment:
      PGADMIN_DEFAULT_EMAIL: user@localhost.localdomain
      PGADMIN_DEFAULT_PASSWORD: password
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_CONFIG_MASTER_PASSWORD_REQUIRED: 'False'
      PGADMIN_CONFIG_WTF_CSRF_ENABLED: 'False'

  prometheus:
    profiles: ['monitoring']
    image: prom/prometheus@sha256:6927e0919a144aa7616fd0137d4816816d42f6b816de3af269ab065250859a62
    restart: unless-stopped
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus

  grafana:  
    profiles: ['monitoring']
    image: grafana/grafana@sha256:8b37a2f028f164ce7b9889e1765b9d6ee23fec80f871d156fbf436d6198d32b7
    depends_on:
      - prometheus
    restart: unless-stopped
    ports:
      - 8013:3000
    environment:
      GF_AUTH_ANONYMOUS_ENABLED: true
    volumes:
      - ./monitoring/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./monitoring/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - grafana-data:/var/lib/grafana
    links:
      - prometheus

volumes:
  db-data:
    driver: local
  grafana-data:
    driver: local
  node_modules-data:
    driver: local
  project-data:
    driver: local
  project-target-data:
    driver: local
  prometheus-data:
    driver: local
  target:
    driver: local
