name: Build and Deploy

on:
  workflow_dispatch: {}
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'

env:
  PRIVATE_DOCKER_REGISTRY: ${{ secrets.REGISTRY_HOSTNAME }}
  PRIVATE_REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
  PRIVATE_REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
  VERSION: "1.0.${{ github.run_number }}"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      
    - name: Build Container
      run: bin/build-container.sh
  
    - name: Push Container
      run: bin/push-container.sh
